name: CI

on:
  push:
    branches:
      - main
      - uniEmpleos
  pull_request:
    branches:
      - main
      - uniEmpleos

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: cd uniEmpleos && yarn

    - name: Check Node.js and npm versions
      run: |
        node --version
        yarn --version

    - name: Run tests 
      run: cd uniEmpleos && yarn test
