name: CI

on:
  push:
    branches:
      - main
      - uniEmpleos
  pull_request:
    branches:
      - main
      - uniEmpleos

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: yarn

    - name: Install vitest globally
      run: yarn global add vitest

    - name: Check Node.js and npm versions
      run: |
        node --version
        yarn --version

    - name: List installed Node.js modules
      run: ls node_modules

    - name: Run tests with verbose output
      run: cd uniEmpleos && yarn test --verbose
